### ISSUE TITLE
Can we safely assume any new account created will be added in eosio voters table?

### ISSUE THREAD

**Issue by tianyangj** [generEOS/airdrop-tools#2]
Hi, in takeNames.js, you are getting all account names from eosio voters table. I get ~204364 accounts. However if I check eostracker/eospark, I get ~270k accounts. So is reading eosio voters table a reliable way to get all EOS accounts?

**Comment by Khazius** [comment]
That's a good question i'd also like the answer too! The voters table seems
to have account that never voted nor have a proxy, so I'm not sure why the
discrepancy.

**Comment by tianyangj** [comment]
Afaik the only way is to loop through all eosio newaccount action and record account names. I am hoping your way would be an easier way, :).

**Comment by tianyangj** [comment]
Not sure if you have already seen this, https://www.eossnapshots.io/faq/. According to eosnewyork, you can't use voters table to get all accounts. The best bet is to use their csv files for account names, one less step for users to do, :). Thanks for your awesome work on this airdropping tool!
